[package]
name = "jpeg_thumbnails"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
image = "0.24.5"
rayon = "1.6.1"
error-chain = "0.12.4"